[package]
name = "aviutl2-community-translation-companion"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aviutl2 = "0.24.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ureq = "2.12.1"
windows = { version = "0.62.2", features = ["Data_Xml_Dom", "UI_Notifications"] }
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
